# Generated by Django 3.2.5 on 2021-07-14 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='birth date'),
            preserve_default=False,
        ),
    ]
