# Generated by Django 3.2.5 on 2021-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210714_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default=759823561, max_length=12),
            preserve_default=False,
        ),
    ]
