# Generated by Django 3.2.5 on 2021-07-14 16:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210714_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
